[project]
name = "ComfyUI-ShakaNodes"
description = "ShakaNodes: Utility tools for ComfyUI"
version = "0.0.1"
dependencies = ["torch"]

[project.urls]
Repository = "https://github.com/bomborant/ComfyUI-ShakaNodes"

[tool.comfy]
PublisherId = "Bomborant"
DisplayName = "Shaka Nodes"
Icon = ""
